### ISSUE TITLE
Refactor Tasks

### ISSUE THREAD

**Issue by modmo22** [EECS-581-Cool-Kids/Battleship-Project-2#13]
This is a tracking ticket of small refactoring tasks we could knock out. The idea is to make a new issue for each task here and not create a branch from this ticket. Feel free to add to and/or tackle these tasks at your convenience if you want to contribute more hours or story points during this phase.

- Adding .sh, .bat and/or .ps1 scripts to initiate starting the necessary terminals during testing and during actual play. This was supposed to have been merged directly into main a few days ago, but got lost in the sauce.
-

**Comment by richardmoser** [comment]
I'm pretty sure I added my script to the comments (and maybe also documentation) branch
